const moviesData = [
    {
        id: "designated",
        title: "Designated Survivor",
        description: "Un membro del gabinetto diventa improvvisamente Presidente degli Stati Uniti dopo un attacco che uccide la maggior parte del governo. L'uomo deve imparare rapidamente il nuovo lavoro e a lottare contro gli orrori futuri.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/designeted.jpg",
        year: "2016",
        duration: "1h 54m",
        regia: "Chris Grismer",
        cast: "Kiefer McLachlan, Natascha McElhone, Italia Ricci",
        genere: "Drama, Thriller, Action"
    },
    {
        id: "lacasa",
        title: "La Casa de Papel",
        description: "Un enigmatico professore recluta otto persone con abilità uniche per rapinare la Zecca di Stato spagnola, dando vita a un elaborato piano che sfida la polizia e l'opinione pubblica.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/lacasa.jpg",
        year: "2017",
        duration: "1h 50m",
        regia: "Álex Pina",
        cast: "Álvaro Morte, Úrsula Corberó, Pedro Alonso",
        genere: "Action, Crime, Drama"
    },
    {
        id: "lucifer",
        title: "Lucifer",
        description: "Lucifero lascia l'Inferno per vivere a Los Angeles e gestire un nightclub, ma presto diventa consulente della polizia.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/lucifer.jpg",
        year: "2020",
        duration: "2h 00m",
        regia: "Tom Kapinos",
        cast: "Tom Ellis, Lauren German",
        genere: "Crime, Drama, Fantasy"
    },
    {
        id: "laregina",
        title: "La Regina degli Scacchi",
        description: "Beth Harmon, un'orfana prodigio degli scacchi, lotta contro le dipendenze mentre cerca di diventare la miglior scacchista del mondo.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/laregina.jpg",
        year: "2020",
        duration: "1h 45m",
        regia: "Scott Frank",
        cast: "Anya Taylor-Joy, Bill Camp, Marielle Heller",
        genere: "Drammatico, Biografico"
    },
    {
        id: "outerbanks",
        title: "Outer Banks",
        description: "Un gruppo di adolescenti della Carolina del Nord scopre una mappa del tesoro che svela un segreto di famiglia e dà il via a una pericolosa avventura.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/outerbanks.jpg",
        year: "2020",
        duration: "1h 40m",
        regia: "Shannon Burke, Jonas Pate",
        cast: "Chase Stokes, Madelyn Cline, Madison Bailey",
        genere: "Azione, Avventura, Dramma"
    },
    {
        id: "peaky",
        title: "Peaky Blinders",
        description: "Nel dopoguerra, la famiglia Shelby guida una gang criminale a Birmingham, espandendo la propria influenza in un mondo di violenza e politica.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/peaky.jpg",
        year: "2013",
        duration: "1h 55m",
        regia: "Steven Knight",
        cast: "Cillian Murphy, Paul Anderson, Helen McCrory",
        genere: "Crimine, Dramma, Storico"
    },
    {
        id: "prison",
        title: "Prison Break",
        description: "Un uomo entra deliberatamente in prigione per salvare il fratello condannato a morte, dando il via a un complesso piano di fuga.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/prison.jpg",
        year: "2005",
        duration: "2h 10m",
        regia: "Paul Scheuring",
        cast: "Wentworth Miller, Dominic Purcell, Sarah Wayne Callies",
        genere: "Azione, Crimine, Dramma"
    },
    {
        id: "squidgame",
        title: "Squid Game",
        description: "Centinaia di persone indebitate partecipano a giochi mortali per vincere un premio in denaro, ma ogni prova potrebbe essere l’ultima.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/squidgame.jpg",
        year: "2021",
        duration: "1h 55m",
        regia: "Hwang Dong-hyuk",
        cast: "Lee Jung-jae, Park Hae-soo, HoYeon Jung",
        genere: "Thriller, Drammatico, Sopravvivenza"
    },
    {
        id: "strangerthings",
        title: "Stranger Things",
        description: "Un ragazzo scompare in una cittadina dell'Indiana, mentre i suoi amici scoprono una ragazza con poteri paranormali e un mondo oscuro nascosto.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/strangerthings.jpg",
        year: "2016",
        duration: "2h 00m",
        regia: "Duffer Brothers",
        cast: "Millie Bobby Brown, Finn Wolfhard, Winona Ryder",
        genere: "Fantascienza, Horror, Drammatico"
    },
    {
        id: "suits",
        title: "Suits",
        description: "Mike Ross, un brillante truffatore con una memoria fotografica, viene assunto da un avvocato di successo nonostante non abbia una laurea in legge.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/suits.jpg",
        year: "2011",
        duration: "1h 50m",
        regia: "Aaron Korsh",
        cast: "Gabriel Macht, Patrick J. Adams, Meghan Markle",
        genere: "Dramma, Legale"
    },
    {
        id: "theoffice",
        title: "The Office",
        description: "Un finto documentario che racconta la vita quotidiana dei dipendenti della Dunder Mifflin, una società che vende carta. Umorismo assurdo e momenti toccanti si mescolano perfettamente.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/theoffice.jpg",
        year: "2005",
        duration: "1h 45m",
        regia: "Greg Daniels",
        cast: "Steve Carell, Rainn Wilson, John Krasinski",
        genere: "Commedia, Mockumentary"
    },
    {
        id: "bigbang",
        title: "The Big Bang Theory",
        description: "Un gruppo di brillanti ma socialmente impacciati scienziati affronta la vita quotidiana e le relazioni, tra scienza, geek culture e situazioni comiche.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/bigbang.jpg",
        year: "2007",
        duration: "1h 50m",
        regia: "Chuck Lorre, Bill Prady",
        cast: "Jim Parsons, Johnny Galecki, Kaley Cuoco",
        genere: "Commedia, Sitcom"
    },
    {
        id: "brooklyn",
        title: "Brooklyn Nine-Nine",
        description: "Un detective brillante ma immaturo lavora in un distretto di polizia di Brooklyn, tra casi criminali e situazioni esilaranti.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/brooklyn.jpg",
        year: "2013",
        duration: "1h 45m",
        regia: "Dan Goor, Michael Schur",
        cast: "Andy Samberg, Andre Braugher, Terry Crews",
        genere: "Commedia, Crime"
    },
    {
        id: "drhouse",
        title: "Dr. House - Medical Division",
        description: "Il geniale ma antisociale dottor Gregory House guida un team di diagnosti affrontando casi medici complessi e misteriosi.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/drhouse.jpg",
        year: "2004",
        duration: "1h 55m",
        regia: "David Shore",
        cast: "Hugh Laurie, Omar Epps, Robert Sean Leonard",
        genere: "Dramma, Medico"
    },
    {
        id: "friends",
        title: "Friends",
        description: "Sei amici affrontano la vita, l'amore e il lavoro a New York City, creando momenti iconici e divertenti lungo il percorso.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/friends.jpg",
        year: "1994",
        duration: "1h 40m",
        regia: "David Crane, Marta Kauffman",
        cast: "Jennifer Aniston, Courteney Cox, Matt LeBlanc",
        genere: "Commedia, Sitcom"
    },
    {
        id: "gossip",
        title: "Gossip Girl",
        description: "Gli scandali e le vite glamour di un gruppo di adolescenti dell'élite di Manhattan vengono svelati da un blog misterioso: Gossip Girl.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/gossip.jpg",
        year: "2007",
        duration: "1h 40m",
        regia: "Josh Schwartz, Stephanie Savage",
        cast: "Blake Lively, Leighton Meester, Penn Badgley",
        genere: "Dramma, Teen"
    },
    {
        id: "resident",
        title: "The Resident",
        description: "Un giovane medico affronta le dure verità del sistema sanitario americano, tra etica, chirurgia e casi difficili.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/resident.jpg",
        year: "2018",
        duration: "1h 50m",
        regia: "Amy Holden Jones",
        cast: "Matt Czuchry, Emily VanCamp, Bruce Greenwood",
        genere: "Dramma, Medico"
    },
    {
        id: "thegood",
        title: "The Good Doctor",
        description: "Shaun Murphy, un giovane chirurgo con autismo e sindrome del savant, deve dimostrare le sue straordinarie capacità in un prestigioso ospedale.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/thegood.jpg",
        year: "2017",
        duration: "1h 55m",
        regia: "David Shore",
        cast: "Freddie Highmore, Antonia Thomas, Hill Harper",
        genere: "Dramma, Medico"
    },
    {
        id: "vpervendetta",
        title: "V per Vendetta",
        description: "In un futuro totalitario, un vigilante mascherato noto come 'V' scatena una rivoluzione contro il regime oppressivo. Una giovane donna si unisce alla sua causa per la libertà.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/vpervendetta.jpg",
        year: "2005",
        duration: "2h 13m",
        regia: "James McTeigue",
        cast: "Natalie Portman, Hugo Weaving",
        genere: "Azione, Drammatico, Thriller"
    },
    {
        id: "americansniper",
        title: "American Sniper",
        description: "La vera storia di Chris Kyle, un cecchino della Marina degli Stati Uniti noto per la sua precisione letale. Combattuto tra dovere e famiglia, affronta le conseguenze psicologiche della guerra.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/americansniper.jpg",
        year: "2014",
        duration: "2h 12m",
        regia: "Clint Eastwood",
        cast: "Bradley Cooper, Sienna Miller",
        genere: "Biografico, Guerra, Drammatico"
    },
    {
        id: "fugadaalcatraz",
        title: "Fuga da Alcatraz",
        description: "Basato su eventi reali, racconta la storia dell'unica fuga riuscita dalla famigerata prigione di massima sicurezza di Alcatraz, orchestrata da tre detenuti.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/fugadaalcatraz.jpg",
        year: "1979",
        duration: "1h 52m",
        regia: "Don Siegel",
        cast: "Clint Eastwood, Patrick McGoohan",
        genere: "Thriller, Drammatico, Crimine"
    },
    {
        id: "interstellar",
        title: "Interstellar",
        description: "Un gruppo di astronauti attraversa un wormhole nello spazio nel tentativo di trovare un nuovo pianeta abitabile per l'umanità, in un'epica odissea tra scienza e sentimenti.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/interstellar.jpg",
        year: "2014",
        duration: "2h 49m",
        regia: "Christopher Nolan",
        cast: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
        genere: "Fantascienza, Drammatico, Avventura"
    },
    {
        id: "ilgladiatore",
        title: "Il Gladiatore",
        description: "Un generale romano tradito diventa schiavo e poi gladiatore, cercando vendetta contro l'imperatore che ha ucciso la sua famiglia.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/ilgladiatore.jpg",
        year: "2000",
        duration: "2h 35m",
        regia: "Ridley Scott",
        cast: "Russell Crowe, Joaquin Phoenix",
        genere: "Storico, Drammatico, Azione"
    },
    {
        id: "ildomanitradinoi",
        title: "Il Domani tra di Noi",
        description: "Due estranei sopravvivono a un incidente aereo e devono affrontare la natura selvaggia e le proprie differenze per sopravvivere e tornare alla civiltà.",
        imgSrc: "./IMG/IMG-MOVIES-ORIZZONTALI/ildomanitradinoi.jpg",
        year: "2017",
        duration: "1h 52m",
        regia: "Hany Abu-Assad",
        cast: "Kate Winslet, Idris Elba",
        genere: "Avventura, Drammatico, Romantico"
    }

];